App/__init__.py
from flask import Flask
from pymongo import MongoClient

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '085c7f29d2d74642'
    app.config['MONGO_URI'] = 'mongodb://localhost:27017/todo_db'

    client = MongoClient(app.config['MONGO_URI'])
    app.db = client.todo_db

    from App.routes import main
    app.register_blueprint(main)

    return app

App/routes.py
import os
from bson.objectid import ObjectId
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app

main = Blueprint('main',__name__)

@main.route('/')
def index():
    tasks = current_app.db.tasks.find()
    return render_template('index.html', tasks = tasks)

@main.route('/add_task', methods=['POST'])
def add_task():
    task_content = request.form.get('content')
    if task_content:
        current_app.db.tasks.insert_one({'content': task_content, 'completed': False})
        flash('Task added successfully!', 'success')
    return redirect(url_for('main.index'))

@main.route('/complete_task/<task_id>')
def complete_task(task_id):
    current_app.db.tasks.update_one({'_id': ObjectId(task_id)}, {'$set': {'completed': True}})
    flash('Task marked as completed!', 'success')
    return redirect(url_for('main.index'))

@main.route('/delete_task/<task_id>')
def delete_task(task_id):
    current_app.db.tasks.delete_one({'_id': ObjectId(task_id)})
    flash('Task deleted successfully!', 'success')
    return redirect(url_for('main.index'))

@main.route('/update_task/<task_id>',methods=['GET','POST'])
def update_task(task_id):
    if request.method == 'POST':
        new_conetent = request.form.get('content')
        if new_conetent:
            current_app.db.tasks.update_one({'_id':ObjectId(task_id)},{'$set':{'content' : new_conetent}})
            flash('Task Updated Successfully!','success')
        return redirect(url_for('main.index'))
    task = current_app.db.tasks.find_one({'_id':ObjectId(task_id)})
    return render_template('update.html',task = task)

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}To-Do List{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="bg-light navbar navbar-expand-lg navbar-light">
        <a class="mx-auto navbar-brand" href="{{ url_for('main.index') }}">
            <h2 class="fw-bold">To-Do List</h2>
        </a>
    </nav>
    <div class="mt-4 container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="mt-4 alert alert-dismissible fade show">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

App/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="mt-4">
    <form method="POST" action="{{ url_for('main.add_task') }}">
        <div class="form-group">
            <input type="text" class="form-control" name="content" placeholder="Enter your task here">
        </div>
        <button type="submit" class="btn btn-primary">Add Task</button>
    </form>
    <h2 class="mt-4">Tasks</h2>
    <ul class="list-group">
        {% for task in tasks %}
            <li class="d-flex justify-content-between align-items-center list-group-item">
                {% if task.completed %}
                    <s>{{ task.content }}</s>
                {% else %}
                    {{ task.content }}
                {% endif %}
                <div>
                    {% if not task.completed == True %}
                        <a href="{{ url_for('main.update_task', task_id=task._id) }}" class="btn btn-sm btn-warning">Update</a>
                    {% endif %}
                    {% if not task.completed %}
                        <a href="{{ url_for('main.complete_task', task_id=task._id) }}" class="btn btn-sm btn-success">Complete</a>
                    {% endif %}
                    <a href="{{ url_for('main.delete_task', task_id=task._id) }}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

App/templates/update.html
{% extends "base.html" %}
{% block title %}Update Task{% endblock %}
{% block content %}
<div class="mt-4">
    <h2>Edit Task</h2>
    <form method="POST" action="{{ url_for('main.update_task', task_id=task._id) }}">
        <div class="form-group">
            <input type="text" class="form-control" name="content" value="{{ task.content }}" placeholder="Enter new task content">
        </div>
        <button type="submit" class="btn btn-primary">Update Task</button>
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}